version: "3"
services:
  nginx:
    image: 338196870821.dkr.ecr.us-east-1.amazonaws.com/nziswano-nginx:7eb0611df2194cc234bdf567aa3e5ec9b3d42c47
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
  wordpress:
    image: 338196870821.dkr.ecr.us-east-1.amazonaws.com/nziswano-wordpress:7eb0611df2194cc234bdf567aa3e5ec9b3d42c47
    volumes:
       - wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - AUTH_KEY=${AUTH_KEY}
      - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
      - LOGGED_IN_KEY=${LOGGED_IN_KEY}
      - NONCE_KEY=${NONCE_KEY}
      - AUTH_SALT=${AUTH_SALT}
      - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
      - LOGGED_IN_SALT=${LOGGED_IN_SALT}
      - NONCE_SALT=${NONCE_SALT}
      - MY_KEY=${MY_KEY}
      - WP_DEBUG=${WP_DEBUG}
volumes:
  wordpress:
